package DB;
// Generated Jul 2, 2014 10:50:08 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Interfaces generated by hbm2java
 */
public class Interfaces  implements java.io.Serializable {


     private Integer id;
     private String url;
     private String displayName;
     private Set privilages = new HashSet(0);

    public Interfaces() {
    }

	
    public Interfaces(String url, String displayName) {
        this.url = url;
        this.displayName = displayName;
    }
    public Interfaces(String url, String displayName, Set privilages) {
       this.url = url;
       this.displayName = displayName;
       this.privilages = privilages;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public Set getPrivilages() {
        return this.privilages;
    }
    
    public void setPrivilages(Set privilages) {
        this.privilages = privilages;
    }




}


