package DB;
// Generated Jul 2, 2014 10:50:08 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LoginSession generated by hbm2java
 */
public class LoginSession  implements java.io.Serializable {


     private Integer id;
     private UserLogin userLogin;
     private String ipAddress;
     private Date inTime;
     private Date outTime;
     private Set sessionActivitieses = new HashSet(0);

    public LoginSession() {
    }

	
    public LoginSession(UserLogin userLogin, String ipAddress, Date inTime, Date outTime) {
        this.userLogin = userLogin;
        this.ipAddress = ipAddress;
        this.inTime = inTime;
        this.outTime = outTime;
    }
    public LoginSession(UserLogin userLogin, String ipAddress, Date inTime, Date outTime, Set sessionActivitieses) {
       this.userLogin = userLogin;
       this.ipAddress = ipAddress;
       this.inTime = inTime;
       this.outTime = outTime;
       this.sessionActivitieses = sessionActivitieses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    public Date getInTime() {
        return this.inTime;
    }
    
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }
    public Date getOutTime() {
        return this.outTime;
    }
    
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }
    public Set getSessionActivitieses() {
        return this.sessionActivitieses;
    }
    
    public void setSessionActivitieses(Set sessionActivitieses) {
        this.sessionActivitieses = sessionActivitieses;
    }




}


