package DB;
// Generated Jul 2, 2014 10:50:08 AM by Hibernate Tools 3.6.0



/**
 * Privilage generated by hbm2java
 */
public class Privilage  implements java.io.Serializable {


     private Integer id;
     private Interfaces interfaces;
     private UserType userType;

    public Privilage() {
    }

    public Privilage(Interfaces interfaces, UserType userType) {
       this.interfaces = interfaces;
       this.userType = userType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Interfaces getInterfaces() {
        return this.interfaces;
    }
    
    public void setInterfaces(Interfaces interfaces) {
        this.interfaces = interfaces;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }




}


