package DB;
// Generated Jul 2, 2014 10:50:08 AM by Hibernate Tools 3.6.0



/**
 * SessionActivities generated by hbm2java
 */
public class SessionActivities  implements java.io.Serializable {


     private Integer id;
     private LoginSession loginSession;
     private String activityDes;

    public SessionActivities() {
    }

    public SessionActivities(LoginSession loginSession, String activityDes) {
       this.loginSession = loginSession;
       this.activityDes = activityDes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public LoginSession getLoginSession() {
        return this.loginSession;
    }
    
    public void setLoginSession(LoginSession loginSession) {
        this.loginSession = loginSession;
    }
    public String getActivityDes() {
        return this.activityDes;
    }
    
    public void setActivityDes(String activityDes) {
        this.activityDes = activityDes;
    }




}


