package DB;
// Generated Jul 2, 2014 10:50:08 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UserLogin generated by hbm2java
 */
public class UserLogin  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String username;
     private String password;
     private Set loginSessions = new HashSet(0);

    public UserLogin() {
    }

	
    public UserLogin(User user, String username, String password) {
        this.user = user;
        this.username = username;
        this.password = password;
    }
    public UserLogin(User user, String username, String password, Set loginSessions) {
       this.user = user;
       this.username = username;
       this.password = password;
       this.loginSessions = loginSessions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getLoginSessions() {
        return this.loginSessions;
    }
    
    public void setLoginSessions(Set loginSessions) {
        this.loginSessions = loginSessions;
    }




}


