package DB;
// Generated Jul 2, 2014 10:50:08 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType  implements java.io.Serializable {


     private Integer id;
     private String typeName;
     private Set privilages = new HashSet(0);
     private Set users = new HashSet(0);

    public UserType() {
    }

	
    public UserType(String typeName) {
        this.typeName = typeName;
    }
    public UserType(String typeName, Set privilages, Set users) {
       this.typeName = typeName;
       this.privilages = privilages;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public Set getPrivilages() {
        return this.privilages;
    }
    
    public void setPrivilages(Set privilages) {
        this.privilages = privilages;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


